ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = /home/$(USER)/Arduino/libraries
BOARD_TAG = uno

include ./Downloads/arduino-ide_2.0.4_Linux_64bit/resources/app/Arduino-Makefile/Arduino.mk